### ISSUE TITLE
test_AnA test case fails with KeyError: "['index'] not found in axis"

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/t-route#617]
I followed the readme's Usage and Testing section to install t-route plus installed the python packages `geopandas`, `deprecated`, `pyarrow` manually. Post install, I attempted to run the `test_AnA` test case but ran into a `KeyError: "['index'] not found in axis"` error during the preprocessing phase of the test. See the below output:

<details>
<summary>Shell output</summary>

```shell
python -m nwm_routing -f -V3 test_AnA.yaml
2023-06-26 19:50:28,116   DEBUG [input.py:199 -         check_inputs()]: ***** Begining configuration file (.YAML) check *****
2023-06-26 19:50:28,116   DEBUG [input.py:105 -     _does_file_exist()]: Checking that a geo_file_path parameter is specified and the file exists
2023-06-26 19:50:28,116   DEBUG [input.py:136 -     _does_file_exist()]: The geo_file_path parameter is specified and exists
2023-06-26 19:50:28,116   DEBUG [input.py:105 -     _does_file_exist()]: Checking that a mask_file_path parameter is specified and the file exists
2023-06-26 19:50:28,116   DEBUG [input.py:136 -     _does_file_exist()]: The mask_file_path parameter is specified and exists
2023-06-26 19:50:28,116   DEBUG [input.py:105 -     _does_file_exist()]: Checking that a level_pool_waterbody_parameter_file_path parameter is specified and the file exists
2023-06-26 19:50:28,116   DEBUG [input.py:136 -     _does_file_exist()]: The level_pool_waterbody_parameter_file_path parameter is specified and exists
2023-06-26 19:50:28,116   DEBUG [input.py:105 -     _does_file_exist()]: Checking that a wrf_hydro_channel_restart_file parameter is specified and the file exists
2023-06-26 19:50:28,116   DEBUG [input.py:136 -     _does_file_exist()]: The wrf_hydro_channel_restart_file parameter is specified and exists
2023-06-26 19:50:28,116   DEBUG [input.py:105 -     _does_file_exist()]: Checking that a wrf_hydro_waterbody_ID_crosswalk_file parameter is specified and the file exists
2023-06-26 19:50:28,116   DEBUG [input.py:136 -     _does_file_exist()]: The wrf_hydro_waterbody_ID_crosswalk_file parameter is specified and exists
2023-06-26 19:50:28,116   DEBUG [input.py:105 -     _does_file_exist()]: Checking that a wrf_hydro_waterbody_crosswalk_filter_file parameter is specified and the file exists
2023-06-26 19:50:28,116   DEBUG [input.py:136 -     _does_file_exist()]: The wrf_hydro_waterbody_crosswalk_filter_file parameter is specified and exists
2023-06-26 19:50:28,116   DEBUG [input.py:154 -     _does_path_exist()]: Checking that a qlat_input_folder parameter is specified and that the directory exists
2023-06-26 19:50:28,116   DEBUG [input.py:183 -     _does_path_exist()]: The qlat_input_folder parameter is specified and exists
2023-06-26 19:50:28,116   DEBUG [input.py:386 -         check_inputs()]: streamflow_nudging == True, so simulation will include streamflow DA
2023-06-26 19:50:28,116   DEBUG [input.py:154 -     _does_path_exist()]: Checking that a usgs_timeslices_folder parameter is specified and that the directory exists
2023-06-26 19:50:28,116   DEBUG [input.py:183 -     _does_path_exist()]: The usgs_timeslices_folder parameter is specified and exists
2023-06-26 19:50:28,116   DEBUG [input.py:105 -     _does_file_exist()]: Checking that a gage_segID_crosswalk_file parameter is specified and the file exists
2023-06-26 19:50:28,116   DEBUG [input.py:136 -     _does_file_exist()]: The gage_segID_crosswalk_file parameter is specified and exists
2023-06-26 19:50:28,116   DEBUG [input.py:105 -     _does_file_exist()]: Checking that a wrf_hydro_lastobs_file parameter is specified and the file exists
2023-06-26 19:50:28,117   DEBUG [input.py:136 -     _does_file_exist()]: The wrf_hydro_lastobs_file parameter is specified and exists
2023-06-26 19:50:28,117   DEBUG [input.py:424 -         check_inputs()]: No LastObs output folder specified. LastObs data will not be written out.
2023-06-26 19:50:28,117   DEBUG [input.py:447 -         check_inputs()]: reservoir_persistence_usgs == True, so simulation will include USGS persistence reservoir DA
2023-06-26 19:50:28,117   DEBUG [input.py:154 -     _does_path_exist()]: Checking that a usgs_timeslices_folder parameter is specified and that the directory exists
2023-06-26 19:50:28,117   DEBUG [input.py:183 -     _does_path_exist()]: The usgs_timeslices_folder parameter is specified and exists
2023-06-26 19:50:28,117   DEBUG [input.py:458 -         check_inputs()]: reservoir_persistence_usace == True, so simulation will include USACE persistence reservoir DA
2023-06-26 19:50:28,117   DEBUG [input.py:154 -     _does_path_exist()]: Checking that a usace_timeslices_folder parameter is specified and that the directory exists
2023-06-26 19:50:28,117   DEBUG [input.py:183 -     _does_path_exist()]: The usace_timeslices_folder parameter is specified and exists
2023-06-26 19:50:28,117   DEBUG [input.py:105 -     _does_file_exist()]: Checking that a gage_lakeID_crosswalk_file parameter is specified and the file exists
2023-06-26 19:50:28,117   DEBUG [input.py:136 -     _does_file_exist()]: The gage_lakeID_crosswalk_file parameter is specified and exists
2023-06-26 19:50:28,117   DEBUG [input.py:494 -         check_inputs()]: No csv output folder specified. Results will NOT be written to csv
2023-06-26 19:50:28,117   DEBUG [input.py:516 -         check_inputs()]: No chrtout_output parameter specified. Results will NOT be written to CHRTOUT
2023-06-26 19:50:28,117   DEBUG [input.py:543 -         check_inputs()]: No hydro_rst_output parameter specified. Restart data will NOT be written out
2023-06-26 19:50:28,117   DEBUG [input.py:551 -         check_inputs()]: ***** Configuration file check complete *****
2023-06-26 19:50:28,117    INFO [preprocess.py:156 - nwm_network_preprocess()]: No diffusive domain file specified in configuration file. This is an MC-only simulation
2023-06-26 19:50:28,117    INFO [preprocess.py:193 - nwm_network_preprocess()]: No refactored diffusive domain file specified in configuration file. This is an MC-only simulation
2023-06-26 19:50:28,117    INFO [preprocess.py:208 - nwm_network_preprocess()]: creating network connections graph
2023-06-26 19:50:28,172   DEBUG [preprocess.py:242 - nwm_network_preprocess()]: network connections graph created in 0.054735660552978516 seconds.
2023-06-26 19:50:28,185    INFO [preprocess.py:439 - nwm_network_preprocess()]: organizing connections into reaches ...
2023-06-26 19:50:28,200   DEBUG [preprocess.py:455 - nwm_network_preprocess()]: reach organization complete in 0.01501011848449707 seconds.
2023-06-26 19:50:28,201    INFO [preprocess.py:657 - nwm_initial_warmstate_preprocess()]: setting waterbody initial states ...
2023-06-26 19:50:28,214   DEBUG [preprocess.py:705 - nwm_initial_warmstate_preprocess()]: waterbody initial states complete in 0.013256072998046875 seconds.
2023-06-26 19:50:28,214    INFO [preprocess.py:716 - nwm_initial_warmstate_preprocess()]: setting channel initial states ...
2023-06-26 19:50:28,243   DEBUG [preprocess.py:786 - nwm_initial_warmstate_preprocess()]: channel initial states complete in 0.0286867618560791 seconds.
2023-06-26 19:50:28,255 WARNING [nhd_network_utilities_v02.py:483 - _check_timeslice_exists()]: Missing TimeSlice file usgs_TimeSlice/2021-08-21_13:00:00.15min.usgsTimeSlice.ncdf
... truncated for reading pleasure
2023-06-26 19:50:28,268 WARNING [nhd_network_utilities_v02.py:483 - _check_timeslice_exists()]: Missing TimeSlice file usace_TimeSlice/2021-08-24_14:00:00.15min.usaceTimeSlice.ncdf
2023-06-26 19:50:28,268    INFO [preprocess.py:901 - nwm_forcing_preprocess()]: Creating a DataFrame of lateral inflow forcings ...
2023-06-26 19:50:30,189   DEBUG [preprocess.py:909 - nwm_forcing_preprocess()]: lateral inflow DataFrame creation complete in 1.9204516410827637 seconds.
2023-06-26 19:50:30,189    INFO [preprocess.py:934 - nwm_forcing_preprocess()]: Creating a DataFrame of USGS gage observations for streamflow DA ...
2023-06-26 19:50:30,866   DEBUG [preprocess.py:1009 - nwm_forcing_preprocess()]: Streamflow DA USGS observation DataFrame creation complete in 0.677260160446167 seconds.
2023-06-26 19:50:30,867    INFO [preprocess.py:1072 - nwm_forcing_preprocess()]: Creating a DataFrame of USGS gage observations for Reservoir DA ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/t-route/src/troute-nwm/src/nwm_routing/__main__.py", line 2013, in <module>
    main_v03(v_args[1])
  File "/app/t-route/src/troute-nwm/src/nwm_routing/__main__.py", line 1429, in main_v03
    ) = nwm_forcing_preprocess(
  File "/app/t-route/src/troute-nwm/src/nwm_routing/preprocess.py", line 1095, in nwm_forcing_preprocess
    usgs_df_15min.join(link_lake_df, how = 'inner').
  File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 5258, in drop
    return super().drop(
  File "/usr/local/lib/python3.8/site-packages/pandas/core/generic.py", line 4549, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/generic.py", line 4591, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6696, in drop
    raise KeyError(f"{list(labels[mask])} not found in axis")
KeyError: "['index'] not found in axis"
```

</details>

<details>
<summary>System Information</summary>

```
CPU Architecture: aarch64
Operating System: Linux
Kernel   Version: 5.15.49-linuxkit
Linux     Distro: Debian 11 (bullseye)
```

</details>

<details>
<summary>Dependency Versions</summary>

```
Python Version: 3.8.17
gdal   Version: 3.2.2
HDF5   Version: 1.10.6
netCDF Version: 4.7.4
```

`pip freeze` output:
```shell
attrs==23.1.0
certifi==2023.5.7
cftime==1.6.2
click==8.1.3
click-plugins==1.1.1
cligj==0.7.2
Cython==0.29.35
Deprecated==1.2.14
Fiona==1.9.4.post1
geopandas==0.13.2
importlib-metadata==6.7.0
joblib==1.2.0
netCDF4==1.6.4
numpy==1.24.4
-e git+http://github.com/NOAA-OWP/t-route.git@3530e12831a33057f7a2b304436bcc23baeb4709#egg=nwm_routing&subdirectory=src/troute-nwm
packaging==23.1
pandas==2.0.2
pyarrow==12.0.1
pyproj==3.5.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0
shapely==2.0.1
six==1.16.0
toolz==0.12.0
-e git+http://github.com/NOAA-OWP/t-route.git@3530e12831a33057f7a2b304436bcc23baeb4709#egg=troute.network&subdirectory=src/troute-network
-e git+http://github.com/NOAA-OWP/t-route.git@3530e12831a33057f7a2b304436bcc23baeb4709#egg=troute.routing&subdirectory=src/troute-routing
tzdata==2023.3
wrapt==1.15.0
xarray==2023.1.0
zipp==3.15.0
```

</details>

**Comment by jameshalgren** [comment]
@aaraney This seems to be the result of a duplicate `drop` command. See https://github.com/NOAA-OWP/t-route/pull/660 and https://github.com/JurgenZach-NOAA/t-route-jz1/pull/1/commits/f4edfeca5fe3899e6c6ee1d20f216362e6716a0a

**Comment by JurgenZach-NOAA** [comment]
Root cause evidently fixed: PR 668
