### ISSUE TITLE
Cannot build/install t-route modules using pip >= 23.1

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/t-route#621]
When attempting to build with `pip 23.1`, the follow error occurs

## Current behavior
run `compiler.sh` and get the following error:
```sh
running build_ext
Processing /Users/nelsfrazier/workspace/ngen/utilities/hydrofabric_test/t-route/src/troute-network
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/Users/nelsfrazier/workspace/ngen/utilities/hydrofabric_test/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/nelsfrazier/workspace/ngen/utilities/hydrofabric_test/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/nelsfrazier/workspace/ngen/utilities/hydrofabric_test/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/dk/f2t2z5mx6y161tmr6yyf3vlc0000gp/T/pip-build-env-73sgqv7z/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/dk/f2t2z5mx6y161tmr6yyf3vlc0000gp/T/pip-build-env-73sgqv7z/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/dk/f2t2z5mx6y161tmr6yyf3vlc0000gp/T/pip-build-env-73sgqv7z/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/dk/f2t2z5mx6y161tmr6yyf3vlc0000gp/T/pip-build-env-73sgqv7z/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

## Expected behavior

Successful build/install

## Steps to replicate behavior (include URLs)

1. `pip install -U pip==23.1`
2. `./compiler.sh`

## Screenshots

![image](https://github.com/NOAA-OWP/t-route/assets/5186647/ef4671e1-882d-48c6-b6be-7c22c74c818e)

**Comment by hellkite500** [comment]
Can downgrade pip using
```sh
pip install -U pip==23.0
```
As a temporary workaround.
