### ISSUE TITLE
Error in running

### ISSUE THREAD

**Issue by TrupeshKumarPatel** [NOAA-OWP/t-route#658]
After successful installation, I tried to run a few test cases, and none were running.

## Current behavior

One of the test cases I tried is [test/LowerColorado_TX](https://github.com/NOAA-OWP/t-route/blob/master/test/LowerColorado_TX/test_AnA.yaml).

## Error

```python3
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/nwm_routing/__main__.py", line 2028, in <module>
    main_v04(v_args[1])
  File "/usr/local/lib/python3.9/site-packages/nwm_routing/__main__.py", line 54, in main_v04
    ) = _input_handler_v04(args)
  File "/usr/local/lib/python3.9/site-packages/nwm_routing/input.py", line 44, in _input_handler_v04
    troute_configuration = Config(**data)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 6 validation errors for Config
network_topology_parameters -> supernetwork_parameters -> geo_file_type
  extra fields not permitted (type=value_error.extra)
network_topology_parameters -> waterbody_parameters -> rfc
  extra fields not permitted (type=value_error.extra)
compute_parameters -> data_assimilation_parameters -> streamflow_da -> wrf_hydro_lastobs_file
  extra fields not permitted (type=value_error.extra)
compute_parameters -> data_assimilation_parameters -> reservoir_da -> gage_lakeID_crosswalk_file
  extra fields not permitted (type=value_error.extra)
compute_parameters -> data_assimilation_parameters -> reservoir_da -> reservoir_persistence_usace
  extra fields not permitted (type=value_error.extra)
compute_parameters -> data_assimilation_parameters -> reservoir_da -> reservoir_persistence_usgs
  extra fields not permitted (type=value_error.extra)
```

Originally, I needed to run the NextGen model with [AWI Dataset](https://ciroh-ua-ngen-data.s3.us-east-2.amazonaws.com/AWI-001/AWI_03W_113060_001.tar.gz), but we are getting `Segmentation fault` (issue CIROH-UA/NGIAB-CloudInfra#21). After debugging, it seems the problem could be related to the `t-route`.  In case the `t-route` is not a problem, then I am sure any guidance in other directions will help, too.

**Comment by jameshalgren** [comment]
@TrupeshKumarPatel I believe we can close this issue with #688
