### ISSUE TITLE
Specify numpy version in requirements.txt

### ISSUE THREAD

**Issue by taddyb** [NOAA-OWP/t-route#829]
Creating a fresh virtual env from the `requirements.txt` generates a dependency conflict as there is no numpy version specified. Numpy recently upgraded to v2.0, and required dependencies: pyarrow (required in the `requirements.txt` to be <12.0) and pandas (required in `requirements.txt` to be  >=1.1.5, <=2.2.0) have listed versions compiled with Numpy v1. This causes a conflict and a failure of an xarray import.

## Current behavior

```sh
> source .venv/bin/activate
> python

Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xarray as xr

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<stdin>", line 1, in <module>
  File "/home/tadd.bindas/projects/t-route-dev/.venv/lib/python3.10/site-packages/xarray/__init__.py", line 3, in <module>
    from xarray import testing, tutorial
  File "/home/tadd.bindas/projects/t-route-dev/.venv/lib/python3.10/site-packages/xarray/testing/__init__.py", line 1, in <module>
    from xarray.testing.assertions import (  # noqa: F401
  File "/home/tadd.bindas/projects/t-route-dev/.venv/lib/python3.10/site-packages/xarray/testing/assertions.py", line 8, in <module>
    import pandas as pd
  File "/home/tadd.bindas/projects/t-route-dev/.venv/lib/python3.10/site-packages/pandas/__init__.py", line 23, in <module>
    from pandas.compat import (
  File "/home/tadd.bindas/projects/t-route-dev/.venv/lib/python3.10/site-packages/pandas/compat/__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "/home/tadd.bindas/projects/t-route-dev/.venv/lib/python3.10/site-packages/pandas/compat/pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "/home/tadd.bindas/projects/t-route-dev/.venv/lib/python3.10/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tadd.bindas/projects/t-route-dev/.venv/lib/python3.10/site-packages/xarray/__init__.py", line 3, in <module>
    from xarray import testing, tutorial
  File "/home/tadd.bindas/projects/t-route-dev/.venv/lib/python3.10/site-packages/xarray/testing/__init__.py", line 1, in <module>
    from xarray.testing.assertions import (  # noqa: F401
  File "/home/tadd.bindas/projects/t-route-dev/.venv/lib/python3.10/site-packages/xarray/testing/assertions.py", line 8, in <module>
    import pandas as pd
  File "/home/tadd.bindas/projects/t-route-dev/.venv/lib/python3.10/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/home/tadd.bindas/projects/t-route-dev/.venv/lib/python3.10/site-packages/pandas/core/api.py", line 1, in <module>
    from pandas._libs import (
  File "/home/tadd.bindas/projects/t-route-dev/.venv/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 18, in <module>
    from pandas._libs.interval import Interval
  File "interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

```

## Expected behavior

you to be able to import xarray without errors

## Steps to replicate behavior (include URLs)

1. `pip install -r requirements.txt`
2. `python`
3. `import xarray as xr`

## Screenshots

See Current Behavior

## Recommended action:
Determine a specific version of numpy for t-route to officially support. I FIXED this problem by downgrading my numpy to v1.24.3, however, using <2.0.0 should suffice. The last v1 version is [v1.26.5](https://github.com/numpy/numpy/releases/tag/v1.26.5)

I'm leaving this as an issue rather than a PR as it should be up to the maintainers what version of a dependency to support 👍

**Comment by aaraney** [comment]
Thanks for the exploratory work and writing this, @taddyb! Just to stay on the safe side of supporting older versions of dependencies and transitive dependencies, I suggest for now we pin `numpy~=1.0`.
